// AUTO-GENERATED — do not edit manually. Run `npm run generate:aliases` to regenerate.

export const frameworkAliases: Record<string, string> = {
  "sadimet": "sadimet",
  "s.a.d.i.m.e.t.": "sadimet",
  "obredimet": "obredimet",
  "o.b.r.e.d.i.m.e.t.": "obredimet",
  "design_web": "design_web",
  "design web": "design_web",
  "dragon_dreaming": "dragon_dreaming",
  "dragon dreaming": "dragon_dreaming",
  "theory_u": "theory_u",
  "theory u": "theory_u",
  "sadi_bredim": "sadi_bredim",
  "sadi & bredim": "sadi_bredim",
  "cultural_emergence": "cultural_emergence",
  "cultural emergence": "cultural_emergence",
  "gosadim": "gosadim",
  "go.s.a.d.i.m.": "gosadim",
};

export const principleAliases: Record<string, string> = {
  "princípio 1": "1",
  "princípio 1 - observar e interagir": "1",
  "p1": "1",
  "observar e interagir": "1",
  "principle 1": "1",
  "observe and interact": "1",
  "principio 1": "1",
  "observar e interactuar": "1",
  "princípio 2": "2",
  "princípio 2 - captar e armazenar energia": "2",
  "p2": "2",
  "captar e armazenar energia": "2",
  "principle 2": "2",
  "catch and store energy": "2",
  "principio 2": "2",
  "captar y almacenar energía": "2",
  "princípio 3": "3",
  "princípio 3 - obter um rendimento": "3",
  "p3": "3",
  "obter um rendimento": "3",
  "principle 3": "3",
  "obtain a yield": "3",
  "principio 3": "3",
  "obtener un rendimiento": "3",
  "princípio 4": "4",
  "princípio 4 - aplicar autorregulação e aceitar feedback": "4",
  "p4": "4",
  "aplicar autorregulação e aceitar feedback": "4",
  "principle 4": "4",
  "apply self-regulation and accept feedback": "4",
  "principio 4": "4",
  "aplicar autorregulación y aceptar retroalimentación": "4",
  "princípio 5": "5",
  "princípio 5 - usar e valorizar recursos e serviços renováveis": "5",
  "p5": "5",
  "usar e valorizar recursos e serviços renováveis": "5",
  "principle 5": "5",
  "use and value renewable resources and services": "5",
  "principio 5": "5",
  "usar y valorar recursos y servicios renovables": "5",
  "princípio 6": "6",
  "princípio 6 - não produzir resíduos": "6",
  "p6": "6",
  "não produzir resíduos": "6",
  "principle 6": "6",
  "produce no waste": "6",
  "principio 6": "6",
  "no producir residuos": "6",
  "princípio 7": "7",
  "princípio 7 - design a partir de padrões para detalhes": "7",
  "p7": "7",
  "design a partir de padrões para detalhes": "7",
  "principle 7": "7",
  "design from patterns to details": "7",
  "principio 7": "7",
  "diseñar desde patrones hacia detalles": "7",
  "princípio 8": "8",
  "princípio 8 - integrar ao invés de segregar": "8",
  "p8": "8",
  "integrar ao invés de segregar": "8",
  "principle 8": "8",
  "integrate rather than segregate": "8",
  "principio 8": "8",
  "integrar en lugar de segregar": "8",
  "princípio 9": "9",
  "princípio 9 - usar soluções pequenas e lentas": "9",
  "p9": "9",
  "usar soluções pequenas e lentas": "9",
  "principle 9": "9",
  "use small and slow solutions": "9",
  "principio 9": "9",
  "usar soluciones pequeñas y lentas": "9",
  "princípio 10": "10",
  "princípio 10 - usar e valorizar a diversidade": "10",
  "p10": "10",
  "usar e valorizar a diversidade": "10",
  "principle 10": "10",
  "use and value diversity": "10",
  "principio 10": "10",
  "usar y valorar la diversidad": "10",
  "princípio 11": "11",
  "princípio 11 - usar bordas e valorizar o marginal": "11",
  "p11": "11",
  "usar bordas e valorizar o marginal": "11",
  "principle 11": "11",
  "use edges and value the marginal": "11",
  "principio 11": "11",
  "usar bordes y valorar lo marginal": "11",
  "princípio 12": "12",
  "princípio 12 - usar e responder à mudança de forma criativa": "12",
  "p12": "12",
  "usar e responder à mudança de forma criativa": "12",
  "principle 12": "12",
  "creatively use and respond to change": "12",
  "principio 12": "12",
  "usar y responder al cambio de forma creativa": "12",
};

export const sdgAliases: Record<string, string> = {
  "ods 1": "1",
  "ods 1 - erradicação da pobreza": "1",
  "erradicação da pobreza": "1",
  "sdg 1": "1",
  "no poverty": "1",
  "fin de la pobreza": "1",
  "ods 2": "2",
  "ods 2 - fome zero e agricultura sustentável": "2",
  "fome zero e agricultura sustentável": "2",
  "sdg 2": "2",
  "zero hunger": "2",
  "hambre cero": "2",
  "ods 3": "3",
  "ods 3 - saúde e bem-estar": "3",
  "saúde e bem-estar": "3",
  "sdg 3": "3",
  "good health and well-being": "3",
  "salud y bienestar": "3",
  "ods 4": "4",
  "ods 4 - educação de qualidade": "4",
  "educação de qualidade": "4",
  "sdg 4": "4",
  "quality education": "4",
  "educación de calidad": "4",
  "ods 5": "5",
  "ods 5 - igualdade de gênero": "5",
  "igualdade de gênero": "5",
  "sdg 5": "5",
  "gender equality": "5",
  "igualdad de género": "5",
  "ods 6": "6",
  "ods 6 - água potável e saneamento": "6",
  "água potável e saneamento": "6",
  "sdg 6": "6",
  "clean water and sanitation": "6",
  "agua limpia y saneamiento": "6",
  "ods 7": "7",
  "ods 7 - energia limpa e acessível": "7",
  "energia limpa e acessível": "7",
  "sdg 7": "7",
  "affordable and clean energy": "7",
  "energía asequible y no contaminante": "7",
  "ods 8": "8",
  "ods 8 - trabalho decente e crescimento econômico": "8",
  "trabalho decente e crescimento econômico": "8",
  "sdg 8": "8",
  "decent work and economic growth": "8",
  "trabajo decente y crecimiento económico": "8",
  "ods 9": "9",
  "ods 9 - indústria, inovação e infraestrutura": "9",
  "indústria, inovação e infraestrutura": "9",
  "sdg 9": "9",
  "industry, innovation and infrastructure": "9",
  "industria, innovación e infraestructura": "9",
  "ods 10": "10",
  "ods 10 - redução das desigualdades": "10",
  "redução das desigualdades": "10",
  "sdg 10": "10",
  "reduced inequalities": "10",
  "reducción de las desigualdades": "10",
  "ods 11": "11",
  "ods 11 - cidades e comunidades sustentáveis": "11",
  "cidades e comunidades sustentáveis": "11",
  "sdg 11": "11",
  "sustainable cities and communities": "11",
  "ciudades y comunidades sostenibles": "11",
  "ods 12": "12",
  "ods 12 - consumo e produção responsáveis": "12",
  "consumo e produção responsáveis": "12",
  "sdg 12": "12",
  "responsible consumption and production": "12",
  "producción y consumo responsables": "12",
  "ods 13": "13",
  "ods 13 - ação contra a mudança global do clima": "13",
  "ação contra a mudança global do clima": "13",
  "sdg 13": "13",
  "climate action": "13",
  "acción por el clima": "13",
  "ods 14": "14",
  "ods 14 - vida na água": "14",
  "vida na água": "14",
  "sdg 14": "14",
  "life below water": "14",
  "vida submarina": "14",
  "ods 15": "15",
  "ods 15 - vida terrestre": "15",
  "vida terrestre": "15",
  "sdg 15": "15",
  "life on land": "15",
  "vida de ecosistemas terrestres": "15",
  "ods 16": "16",
  "ods 16 - paz, justiça e instituições eficazes": "16",
  "paz, justiça e instituições eficazes": "16",
  "sdg 16": "16",
  "peace, justice and strong institutions": "16",
  "paz, justicia e instituciones sólidas": "16",
  "ods 17": "17",
  "ods 17 - parcerias e meios de implementação": "17",
  "parcerias e meios de implementação": "17",
  "sdg 17": "17",
  "partnerships for the goals": "17",
  "alianzas para lograr los objetivos": "17",
};

export const naturePatternAliases: Record<string, string> = {
  "sun-shade": "sun-shade",
  "sol e sombra": "sun-shade",
  "sun and shade": "sun-shade",
  "sol y sombra": "sun-shade",
  "water": "water",
  "água": "water",
  "agua": "water",
  "wind": "wind",
  "vento": "wind",
  "viento": "wind",
  "topography": "topography",
  "topografia": "topography",
  "topografía": "topography",
  "soil": "soil",
  "solo": "soil",
  "suelo": "soil",
  "vegetation": "vegetation",
  "vegetação existente": "vegetation",
  "existing vegetation": "vegetation",
  "vegetación existente": "vegetation",
  "wildlife": "wildlife",
  "fauna": "wildlife",
  "edges": "edges",
  "bordas e ecótonos": "edges",
  "edges and ecotones": "edges",
  "bordes y ecotonos": "edges",
  "human-use": "human-use",
  "uso humano atual": "human-use",
  "current human use": "human-use",
  "uso humano actual": "human-use",
};

export const designSkillAliases: Record<string, string> = {
  "hydrology": "hydrology",
  "hidrologia": "hydrology",
  "agronomy": "agronomy",
  "agronomia": "agronomy",
  "agroforestry": "agroforestry",
  "sistemas agroflorestais": "agroforestry",
  "soil-science": "soil-science",
  "ciência do solo": "soil-science",
  "architecture": "architecture",
  "arquitetura e bioconstrução": "architecture",
  "ecology": "ecology",
  "ecologia": "ecology",
  "cartography-gis": "cartography-gis",
  "cartografia e geoprocessamento": "cartography-gis",
  "social-facilitation": "social-facilitation",
  "facilitação social e participativa": "social-facilitation",
  "animal-husbandry": "animal-husbandry",
  "manejo animal integrado": "animal-husbandry",
  "energy-systems": "energy-systems",
  "sistemas de energia renovável": "energy-systems",
  "water-treatment": "water-treatment",
  "tratamento de água e efluentes": "water-treatment",
  "botany": "botany",
  "botânica e etnobotânica": "botany",
};

export const ossToolAliases: Record<string, string> = {
  "qgis": "qgis",
  "google-earth": "google-earth",
  "google earth pro": "google-earth",
  "openstreetmap": "openstreetmap",
  "libreoffice-calc": "libreoffice-calc",
  "libreoffice calc": "libreoffice-calc",
  "inkscape": "inkscape",
  "stellarium": "stellarium",
  "f4map": "f4map",
  "climate-data-org": "climate-data-org",
  "climate-data.org": "climate-data-org",
  "open-food-network": "open-food-network",
  "open food network": "open-food-network",
  "inaturalist": "inaturalist",
  "soilgrids": "soilgrids",
  "farmhack": "farmhack",
  "farm hack": "farmhack",
};
