// AUTO-GENERATED — do not edit manually. Run `npm run generate:aliases` to regenerate.

export const frameworkAliases: Record<string, string> = {
  "sadimet": "sadimet",
  "s.a.d.i.m.e.t.": "sadimet",
  "obredimet": "obredimet",
  "o.b.r.e.d.i.m.e.t.": "obredimet",
  "design_web": "design_web",
  "design web": "design_web",
  "dragon_dreaming": "dragon_dreaming",
  "dragon dreaming": "dragon_dreaming",
  "theory_u": "theory_u",
  "theory u": "theory_u",
  "sadi_bredim": "sadi_bredim",
  "sadi & bredim": "sadi_bredim",
  "cultural_emergence": "cultural_emergence",
  "cultural emergence": "cultural_emergence",
  "gosadim": "gosadim",
  "go.s.a.d.i.m.": "gosadim",
};

export const principleAliases: Record<string, string> = {
  "princípio 1": "1",
  "princípio 1 - observar e interagir": "1",
  "p1": "1",
  "observar e interagir": "1",
  "princípio 2": "2",
  "princípio 2 - captar e armazenar energia": "2",
  "p2": "2",
  "captar e armazenar energia": "2",
  "princípio 3": "3",
  "princípio 3 - obter um rendimento": "3",
  "p3": "3",
  "obter um rendimento": "3",
  "princípio 4": "4",
  "princípio 4 - aplicar autorregulação e aceitar feedback": "4",
  "p4": "4",
  "aplicar autorregulação e aceitar feedback": "4",
  "princípio 5": "5",
  "princípio 5 - usar e valorizar recursos e serviços renováveis": "5",
  "p5": "5",
  "usar e valorizar recursos e serviços renováveis": "5",
  "princípio 6": "6",
  "princípio 6 - não produzir resíduos": "6",
  "p6": "6",
  "não produzir resíduos": "6",
  "princípio 7": "7",
  "princípio 7 - design a partir de padrões para detalhes": "7",
  "p7": "7",
  "design a partir de padrões para detalhes": "7",
  "princípio 8": "8",
  "princípio 8 - integrar ao invés de segregar": "8",
  "p8": "8",
  "integrar ao invés de segregar": "8",
  "princípio 9": "9",
  "princípio 9 - usar soluções pequenas e lentas": "9",
  "p9": "9",
  "usar soluções pequenas e lentas": "9",
  "princípio 10": "10",
  "princípio 10 - usar e valorizar a diversidade": "10",
  "p10": "10",
  "usar e valorizar a diversidade": "10",
  "princípio 11": "11",
  "princípio 11 - usar bordas e valorizar o marginal": "11",
  "p11": "11",
  "usar bordas e valorizar o marginal": "11",
  "princípio 12": "12",
  "princípio 12 - usar e responder à mudança de forma criativa": "12",
  "p12": "12",
  "usar e responder à mudança de forma criativa": "12",
};

export const sdgAliases: Record<string, string> = {
  "ods 1": "1",
  "ods 1 - erradicação da pobreza": "1",
  "erradicação da pobreza": "1",
  "ods 2": "2",
  "ods 2 - fome zero e agricultura sustentável": "2",
  "fome zero e agricultura sustentável": "2",
  "ods 3": "3",
  "ods 3 - saúde e bem-estar": "3",
  "saúde e bem-estar": "3",
  "ods 4": "4",
  "ods 4 - educação de qualidade": "4",
  "educação de qualidade": "4",
  "ods 5": "5",
  "ods 5 - igualdade de gênero": "5",
  "igualdade de gênero": "5",
  "ods 6": "6",
  "ods 6 - água potável e saneamento": "6",
  "água potável e saneamento": "6",
  "ods 7": "7",
  "ods 7 - energia limpa e acessível": "7",
  "energia limpa e acessível": "7",
  "ods 8": "8",
  "ods 8 - trabalho decente e crescimento econômico": "8",
  "trabalho decente e crescimento econômico": "8",
  "ods 9": "9",
  "ods 9 - indústria, inovação e infraestrutura": "9",
  "indústria, inovação e infraestrutura": "9",
  "ods 10": "10",
  "ods 10 - redução das desigualdades": "10",
  "redução das desigualdades": "10",
  "ods 11": "11",
  "ods 11 - cidades e comunidades sustentáveis": "11",
  "cidades e comunidades sustentáveis": "11",
  "ods 12": "12",
  "ods 12 - consumo e produção responsáveis": "12",
  "consumo e produção responsáveis": "12",
  "ods 13": "13",
  "ods 13 - ação contra a mudança global do clima": "13",
  "ação contra a mudança global do clima": "13",
  "ods 14": "14",
  "ods 14 - vida na água": "14",
  "vida na água": "14",
  "ods 15": "15",
  "ods 15 - vida terrestre": "15",
  "vida terrestre": "15",
  "ods 16": "16",
  "ods 16 - paz, justiça e instituições eficazes": "16",
  "paz, justiça e instituições eficazes": "16",
  "ods 17": "17",
  "ods 17 - parcerias e meios de implementação": "17",
  "parcerias e meios de implementação": "17",
};

export const naturePatternAliases: Record<string, string> = {
  "sun-shade": "sun-shade",
  "sol e sombra": "sun-shade",
  "water": "water",
  "água": "water",
  "wind": "wind",
  "vento": "wind",
  "topography": "topography",
  "topografia": "topography",
  "soil": "soil",
  "solo": "soil",
  "vegetation": "vegetation",
  "vegetação existente": "vegetation",
  "wildlife": "wildlife",
  "fauna": "wildlife",
  "edges": "edges",
  "bordas e ecótonos": "edges",
  "human-use": "human-use",
  "uso humano atual": "human-use",
};
